config:
  validation: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    active: false
